export enum ViewPermission {
  DASHBOARD_VIEW = 'dashboard.read',
  PRODUCTS_VIEW = 'products.read',
  CATEGORIES_VIEW = 'categories.read',
  STOCKS_VIEW = 'stocks.read',
  STOCK_MOVEMENTS_VIEW = 'stock_movements.read',
  PURCHASE_ORDERS_VIEW = 'purchase_orders.read',
  SUPPLIERS_VIEW = 'suppliers.read',
  PRODUCT_SOURCES_VIEW = 'product_sources.read',
  STORES_VIEW = 'stores.read',
  USERS_VIEW = 'users.read',
  AUDIT_LOGS_VIEW = 'audit_logs.read',
  REPORTS_VIEW = 'reports.read',
  BUSINESS_VIEW = 'businesses.read',
  PROFILE_VIEW = 'profile.read',
}
